import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("hsk20", "routes/hsk20.tsx"),
  route("hsk30", "routes/hsk30.tsx"),
  route("lessons", "routes/lessons._index.tsx"),
  route("lessons/:lessonId", "routes/lessons.$lessonId.tsx"),
  route("roadmap", "routes/roadmap.tsx"),
  route("roadmap/:roadmapId", "routes/roadmap.$roadmapId.tsx"),
  route("profile", "routes/profile.tsx"),
  route("dashboard", "routes/dashboard.tsx"),
  route("ai-assistant", "routes/ai-assistant.tsx"),
  route("ai-practice", "routes/ai-practice.tsx"),
  route("maintenance", "routes/maintenance.tsx"),
  route("admin", "routes/admin.tsx"),
  route("api/auth/login", "routes/api.auth.login.ts"),
  route("api/auth/register", "routes/api.auth.register.ts"),
  route("api/auth/logout", "routes/api.auth.logout.ts"),
  route("api/mobile/auth/login", "routes/api.mobile.auth.login.ts"),
  route("api/mobile/auth/register", "routes/api.mobile.auth.register.ts"),
  route("api/mobile/auth/me", "routes/api.mobile.auth.me.ts"),
  route("api/mobile/lessons", "routes/api.mobile.lessons.ts"),
  route("api/mobile/lessons/:lessonId", "routes/api.mobile.lessons.$lessonId.ts"),
  route("api/mobile/roadmap", "routes/api.mobile.roadmap.ts"),
  route("api/mobile/roadmap/:roadmapId", "routes/api.mobile.roadmap.$roadmapId.ts"),
  route("api/vocabularies/import", "routes/api.vocabularies.import.ts"),
  route("api/ai/chat", "routes/api.ai.chat.ts"),
  route("api/ai/practice", "routes/api.ai.practice.ts"),
  route("api/ai/split-lessons", "routes/api.ai.split-lessons.ts"),
  route("api/ai/tts", "routes/api.ai.tts.ts"),
  route("api/admin/lesson-import", "routes/api.admin.lesson-import.ts"),
  route("api/admin/lesson-import-status", "routes/api.admin.lesson-import-status.ts"),
] satisfies RouteConfig;
