// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/hsk20": {
    params: {};
  };
  "/hsk30": {
    params: {};
  };
  "/lessons": {
    params: {};
  };
  "/lessons/:lessonId": {
    params: {
      "lessonId": string;
    };
  };
  "/roadmap": {
    params: {};
  };
  "/roadmap/:roadmapId": {
    params: {
      "roadmapId": string;
    };
  };
  "/profile": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/ai-assistant": {
    params: {};
  };
  "/ai-practice": {
    params: {};
  };
  "/maintenance": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/api/auth/login": {
    params: {};
  };
  "/api/auth/register": {
    params: {};
  };
  "/api/auth/logout": {
    params: {};
  };
  "/api/mobile/auth/login": {
    params: {};
  };
  "/api/mobile/auth/register": {
    params: {};
  };
  "/api/mobile/auth/me": {
    params: {};
  };
  "/api/mobile/lessons": {
    params: {};
  };
  "/api/mobile/lessons/:lessonId": {
    params: {
      "lessonId": string;
    };
  };
  "/api/mobile/roadmap": {
    params: {};
  };
  "/api/mobile/roadmap/:roadmapId": {
    params: {
      "roadmapId": string;
    };
  };
  "/api/vocabularies/import": {
    params: {};
  };
  "/api/ai/chat": {
    params: {};
  };
  "/api/ai/practice": {
    params: {};
  };
  "/api/ai/split-lessons": {
    params: {};
  };
  "/api/ai/tts": {
    params: {};
  };
  "/api/admin/lesson-import": {
    params: {};
  };
  "/api/admin/lesson-import-status": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/hsk20" | "/hsk30" | "/lessons" | "/lessons/:lessonId" | "/roadmap" | "/roadmap/:roadmapId" | "/profile" | "/dashboard" | "/ai-assistant" | "/ai-practice" | "/maintenance" | "/admin" | "/api/auth/login" | "/api/auth/register" | "/api/auth/logout" | "/api/mobile/auth/login" | "/api/mobile/auth/register" | "/api/mobile/auth/me" | "/api/mobile/lessons" | "/api/mobile/lessons/:lessonId" | "/api/mobile/roadmap" | "/api/mobile/roadmap/:roadmapId" | "/api/vocabularies/import" | "/api/ai/chat" | "/api/ai/practice" | "/api/ai/split-lessons" | "/api/ai/tts" | "/api/admin/lesson-import" | "/api/admin/lesson-import-status";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/hsk20.tsx": {
    id: "routes/hsk20";
    page: "/hsk20";
  };
  "routes/hsk30.tsx": {
    id: "routes/hsk30";
    page: "/hsk30";
  };
  "routes/lessons._index.tsx": {
    id: "routes/lessons._index";
    page: "/lessons";
  };
  "routes/lessons.$lessonId.tsx": {
    id: "routes/lessons.$lessonId";
    page: "/lessons/:lessonId";
  };
  "routes/roadmap.tsx": {
    id: "routes/roadmap";
    page: "/roadmap";
  };
  "routes/roadmap.$roadmapId.tsx": {
    id: "routes/roadmap.$roadmapId";
    page: "/roadmap/:roadmapId";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/ai-assistant.tsx": {
    id: "routes/ai-assistant";
    page: "/ai-assistant";
  };
  "routes/ai-practice.tsx": {
    id: "routes/ai-practice";
    page: "/ai-practice";
  };
  "routes/maintenance.tsx": {
    id: "routes/maintenance";
    page: "/maintenance";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin";
  };
  "routes/api.auth.login.ts": {
    id: "routes/api.auth.login";
    page: "/api/auth/login";
  };
  "routes/api.auth.register.ts": {
    id: "routes/api.auth.register";
    page: "/api/auth/register";
  };
  "routes/api.auth.logout.ts": {
    id: "routes/api.auth.logout";
    page: "/api/auth/logout";
  };
  "routes/api.mobile.auth.login.ts": {
    id: "routes/api.mobile.auth.login";
    page: "/api/mobile/auth/login";
  };
  "routes/api.mobile.auth.register.ts": {
    id: "routes/api.mobile.auth.register";
    page: "/api/mobile/auth/register";
  };
  "routes/api.mobile.auth.me.ts": {
    id: "routes/api.mobile.auth.me";
    page: "/api/mobile/auth/me";
  };
  "routes/api.mobile.lessons.ts": {
    id: "routes/api.mobile.lessons";
    page: "/api/mobile/lessons";
  };
  "routes/api.mobile.lessons.$lessonId.ts": {
    id: "routes/api.mobile.lessons.$lessonId";
    page: "/api/mobile/lessons/:lessonId";
  };
  "routes/api.mobile.roadmap.ts": {
    id: "routes/api.mobile.roadmap";
    page: "/api/mobile/roadmap";
  };
  "routes/api.mobile.roadmap.$roadmapId.ts": {
    id: "routes/api.mobile.roadmap.$roadmapId";
    page: "/api/mobile/roadmap/:roadmapId";
  };
  "routes/api.vocabularies.import.ts": {
    id: "routes/api.vocabularies.import";
    page: "/api/vocabularies/import";
  };
  "routes/api.ai.chat.ts": {
    id: "routes/api.ai.chat";
    page: "/api/ai/chat";
  };
  "routes/api.ai.practice.ts": {
    id: "routes/api.ai.practice";
    page: "/api/ai/practice";
  };
  "routes/api.ai.split-lessons.ts": {
    id: "routes/api.ai.split-lessons";
    page: "/api/ai/split-lessons";
  };
  "routes/api.ai.tts.ts": {
    id: "routes/api.ai.tts";
    page: "/api/ai/tts";
  };
  "routes/api.admin.lesson-import.ts": {
    id: "routes/api.admin.lesson-import";
    page: "/api/admin/lesson-import";
  };
  "routes/api.admin.lesson-import-status.ts": {
    id: "routes/api.admin.lesson-import-status";
    page: "/api/admin/lesson-import-status";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/hsk20": typeof import("./app/routes/hsk20.tsx");
  "routes/hsk30": typeof import("./app/routes/hsk30.tsx");
  "routes/lessons._index": typeof import("./app/routes/lessons._index.tsx");
  "routes/lessons.$lessonId": typeof import("./app/routes/lessons.$lessonId.tsx");
  "routes/roadmap": typeof import("./app/routes/roadmap.tsx");
  "routes/roadmap.$roadmapId": typeof import("./app/routes/roadmap.$roadmapId.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/ai-assistant": typeof import("./app/routes/ai-assistant.tsx");
  "routes/ai-practice": typeof import("./app/routes/ai-practice.tsx");
  "routes/maintenance": typeof import("./app/routes/maintenance.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
  "routes/api.auth.login": typeof import("./app/routes/api.auth.login.ts");
  "routes/api.auth.register": typeof import("./app/routes/api.auth.register.ts");
  "routes/api.auth.logout": typeof import("./app/routes/api.auth.logout.ts");
  "routes/api.mobile.auth.login": typeof import("./app/routes/api.mobile.auth.login.ts");
  "routes/api.mobile.auth.register": typeof import("./app/routes/api.mobile.auth.register.ts");
  "routes/api.mobile.auth.me": typeof import("./app/routes/api.mobile.auth.me.ts");
  "routes/api.mobile.lessons": typeof import("./app/routes/api.mobile.lessons.ts");
  "routes/api.mobile.lessons.$lessonId": typeof import("./app/routes/api.mobile.lessons.$lessonId.ts");
  "routes/api.mobile.roadmap": typeof import("./app/routes/api.mobile.roadmap.ts");
  "routes/api.mobile.roadmap.$roadmapId": typeof import("./app/routes/api.mobile.roadmap.$roadmapId.ts");
  "routes/api.vocabularies.import": typeof import("./app/routes/api.vocabularies.import.ts");
  "routes/api.ai.chat": typeof import("./app/routes/api.ai.chat.ts");
  "routes/api.ai.practice": typeof import("./app/routes/api.ai.practice.ts");
  "routes/api.ai.split-lessons": typeof import("./app/routes/api.ai.split-lessons.ts");
  "routes/api.ai.tts": typeof import("./app/routes/api.ai.tts.ts");
  "routes/api.admin.lesson-import": typeof import("./app/routes/api.admin.lesson-import.ts");
  "routes/api.admin.lesson-import-status": typeof import("./app/routes/api.admin.lesson-import-status.ts");
};